# main.sync 👀</br>

`main.sync`는 제대로 동작하지 않는 코드라고 했습니다.
**정확히는 main 스레드에서 직접 호출하면 안되는 코드입니다.**

플레이 그라운드에서 main.sync를 호출해주면 아래와 같은 에러가 발생합니다.
에러의 이유에 대해서 먼저 알아봅시다.
```swift!
DispatchQueue.main.sync { /* error: error: Execution was interrupted, reason: EXC_BREAKPOINT (code=1, subcode=0x18011922c).
    The process has been left at the point where it was interrupted, use "thread return -x" to return to the state before expression evaluation. */
    for _ in 1...5 {
        print("😀😀😀😀😀")
        sleep(1)
    }
}
```

main.sync를 직접적으로 호출하면 `deadlock(교착상태)`에 빠지게 됩니다.
이는 위에서 언급했던 작업이 끝나기를 기다리지 않는 async의 특성과는 반대되는,
`작업이 끝나기를 기다리는 sync의 특성`때문에 발생합니다.

몇 가지 코드를 작성하면서 sync는 코드 블록이 처리되기 전까지 다음 코드로 넘어가지 않는 것을 확인했습니다.
이러한 상황을 `Block-wait`이라고 합니다.
코드 블록이 끝나기 전까지 그 스레드는 멈춰있겠다는 뜻입니다.
따라서 main 스레드에서 `main.sync`를 호출하게 되면 main 스레드는 sync의 코드 블록이 수행되기를 기다려야 합니다.

하지만 이때 sync의 코드 블록 역시 멈춰버리는 것입니다.
main 스레드에서 실행되고 있던 코드이기 때문입니다.
따라서 아무것도 실행되지 못하고 `main 스레드는 sync가 끝나기를, sync는 main 스레드의 Block-wait이 끝나기`를 기다리는 상태가 되어버립니다.

이러한 현상은 main 큐이기 때문에 발생하는 현상입니다.
만약 Serial 큐를 커스텀하여 sync를 실행한다면 에러는 발생하지 않습니다.
이때는 main 스레드와는 별개의 문제가 되기 때문입니다.

하지만 `main.sync`를 호출할 수 있는 경우도 있습니다.
main 스레드에서 호출하지 않으면 됩니다.
예를 들어 global 스레드에서 `main.sync`를 호출한다면 에러없이 예상대로 동작하는 것을 확인할 수 있습니다.

```swift!
DispatchQueue.global().async {
	DispatchQueue.main.sync {
		for _ in 1...5 {
			print("😀😀😀😀😀")
			sleep(1)
		}
	}
}

for _ in 1...5 {
	print("🥶🥶🥶🥶🥶")
	sleep(2)
}

/* 출력 결과
🥶🥶🥶🥶🥶
🥶🥶🥶🥶🥶
🥶🥶🥶🥶🥶
🥶🥶🥶🥶🥶
🥶🥶🥶🥶🥶
😀😀😀😀😀
😀😀😀😀😀
😀😀😀😀😀
😀😀😀😀😀
😀😀😀😀😀
*/
```
